version: '3'
services:
  db:
    container_name: opac-db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sunctf_2019_hogehoge
      - MYSQL_DATABASE=opac

  web:
    container_name: opac-web
    build: ./web/
    ports:
      - "10004:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=opac
      - MYSQL_USER=root
      - MYSQL_PASSWORD=sunctf_2019_hogehoge
    depends_on:
      - db
